/* Palette generated by Material Palette - materialpalette.com/deep-purple/cyan */

const palette = {
  darkPrimary: '#512DA8',
  defaultPrimary: '#673AB7',
  lightPrimary: '#D1C4E9',
  textPrimary: '#FFFFFF',
  accent: '#00BCD4',
  primaryText: '#212121',
  secondaryText: '#757575',
  divider: '#BDBDBD',
};

export default palette;
